/* FAQ Q&A — verbatim from home-b.jsx FAQ. Shared by FAQ.astro (visible
   accordion) and the FAQPage JSON-LD in the layout so they never drift. */
export const FAQ_DATA: [string, string][] = [
  ["What does the onboarding and support process look like?", "We offer a 'white-glove' setup. A LabsCubed specialist performs on-site installation, calibration to ASTM standards, and team training. Post-installation, we provide prompt remote support and annual on-site calibration services to ensure your equipment remains at peak performance."],
  ["What is the typical ROI for a LabsCubed system?", "Most customers achieve a full return on investment in 18–24 months. This is achieved through labor efficiency — recovering 3–4 hours of technician time daily; 2-in-1 savings — replacing the need for separate tensile and flexure machines with one automated platform; and accuracy — reducing costly scrap and rework by eliminating operator-induced variability."],
  ["How do I access and visualize my test data?", "Data is recorded instantly and can be accessed via the machine's touchscreen or the cloud-based AI Portal. Our software team ensures seamless integration with your existing infrastructure, including Alpha Workbench, Uncountable, SAP, and other LIMS/ERP systems."],
  ["What does LabsCubed do?", "LabsCubed designs and manufactures high-performance automated material testing systems specifically for the rubber and plastics industries. Our flagship products, the CubeOne and CubeTen, automate the entire testing lifecycle — from sample measurement and robotic loading to AI-driven data analysis. By integrating robotics with our proprietary AI Suite, we help global manufacturers eliminate manual bottlenecks and achieve unmatched data consistency."],
  ["Who are LabsCubed products for?", "Our solutions are engineered for Lab Managers, Quality Directors, and R&D Engineers at companies with medium-to-high testing volumes. LabsCubed is the ideal fit for facilities processing 50+ rubber samples or 10+ plastic tensile tests per day. We currently serve industry leaders like Bridgestone, Parker Hannifin, Hexpol, and AirBoss who prioritize high-throughput and operator-independent results."],
  ["What industries do you serve?", "We specialize in the Rubber (Custom Compounding, Elastomers) and Plastics (Compounding, Processing) sectors. Our technology is a staple in the Automotive, Medical Device, Aerospace, Wire & Cable, and Consumer Goods industries, where precision in material properties like tensile and flexure strength is critical for safety and performance."],
  ["What makes LabsCubed different from traditional testing equipment providers?", "Unlike traditional Universal Testing Machines (UTMs) that require a technician to load every sample manually, LabsCubed offers 2-in-1 Intelligent Automation. We combine high-precision hardware for both Tensile and Flexure testing with an AI-driven software ecosystem. This allows for up to 85–95% recovery of technician time, 40% higher data consistency, and conversational data analytics that you won't find in manual systems."],
  ["What are the key differences between the CubeOne and CubeTen?", "CubeOne is best for Rubber and Elastomers. It features a force capacity of up to 1kN and is optimized for high-elongation materials. CubeTen is engineered for Rigid Plastics and High-Strength materials. It provides a force capacity of up to 10kN and supports specialized testing like Single Lap Shear and T-Peel adhesives."],
  ["What types of materials can your systems test?", "Our systems are designed for a vast range of polymers tested at ambient temperatures. Rubber/Elastomers: NR, SBR, EPDM, NBR, and Silicone (VMQ). Plastics: PP, HDPE, PVC, ABS, Polycarbonate (PC), Nylon (PA), POM, PBT, and TPU. Thermosets: Epoxy and Phenolic Resins."],
  ["Which testing standards can your equipment meet?", "LabsCubed systems are fully compliant with major international standards, ensuring easy integration into any certified lab. Tensile: ASTM D412 & ISO 37 (Rubber), ASTM D638 & ISO 527 (Plastics). Flexure: ASTM D790 & ISO 178. Tear: ASTM D624 (Types B and C). Adhesives (CubeTen): Single Lap Shear and T-Peel."],
  ["Does the horizontal design affect accuracy compared to traditional vertical UTMs?", "No. LabsCubed has 10 years of comparative test data proving that our horizontal orientation delivers results identical to traditional vertical machines. This design is what enables our high-speed robotic loading. Our systems are precision-calibrated to ensure gravity and friction have zero impact on load readings, a fact validated by our long-term partnerships with global giants like Bridgestone and Parker Hannifin."],
  ["At what temperature conditions do the machines perform tests?", "LabsCubed systems are optimized for high-throughput testing at standard laboratory ambient temperatures. This focus allows us to provide the fastest, most reliable automated workflow for high-throughput quality control and R&D. We do not currently support extreme high or low temperature testing (e.g., environmental chambers)."],
  ["What is the LabsCubed AI Suite & AI Portal?", "This is our proprietary software ecosystem that transforms your lab into an innovation hub. Key features include AI-Enhanced Vision — precision elongation measurement that ignores marking imperfections, significantly reducing failed tests; Predictive Maintenance — the AI monitors machine health and performs 'self-recovery' for minor issues, minimizing downtime; and Conversational Analytics — through the AI Portal, you can ask your data questions (e.g., 'Compare batch A to batch B') in plain English, rather than manually sorting through spreadsheets."],
];

/* Plastic (CubeTen) FAQ for /plastic-testing — same accordion, plastics-only
   questions. Every claim is taken from copy already on the site (the homepage
   FAQ above, the live CubeTen page and the ASTM D638 resource page), so the
   answers never drift from what the rest of the site says. Also feeds that
   page's FAQPage JSON-LD. */
export const PLASTIC_FAQ_DATA: [string, string][] = [
  ["What is the CubeTen?", "The CubeTen is LabsCubed's automated tensile testing machine for rigid plastics and adhesives. Load up to 15 specimens at once and it measures, grips and pulls each one unattended — with a force capacity of up to 10 kN and elongation up to 1000% — while your team moves on to higher-value work."],
  ["Which testing standards does the CubeTen support?", "Tensile testing to ASTM D638 and ISO 527, as well as DIN and JIS methods. The same machine also runs adhesive tests such as Single Lap Shear and T-Peel without requiring any modifications."],
  ["Which ASTM D638 and ISO 527-2 specimen types can it test?", "All five ASTM D638 geometries — Type I for rigid plastics, Type II for materials that won't break as a Type I, Type III for thick sections up to 14 mm, Type IV for thin plastics and comparisons of different rigidity, and Type V micro-tensile specimens — plus ISO 527-2 Type 1A multipurpose moulded and Type 1B machined specimens."],
  ["What types of plastics can the CubeTen test?", "A wide range of polymers tested at ambient temperature, including PP, HDPE, PVC, ABS, Polycarbonate (PC), Nylon (PA), POM, PBT and TPU, as well as thermosets such as epoxy and phenolic resins."],
  ["Do I need an extensometer for ASTM D638?", "An extensometer is required whenever modulus or strain values are reported. Crosshead displacement is acceptable for basic elongation checks, but it includes machine compliance and will overstate strain. The CubeTen supports crosshead displacement, an automated physical extensometer, and a video extensometer."],
  ["How does automation improve plastic tensile test repeatability?", "Manual positioning, gauge marking and clamping are the main sources of test-to-test variation. The CubeTen measures width and thickness with calibrated sensors, auto-aligns each specimen in the grips and applies a consistent gripping force, so the operator is removed from the result — delivering up to 40% more consistent data."],
  ["Is the CubeTen right for my lab's testing volume?", "The CubeTen is built for Lab Managers, Quality Directors and R&D Engineers at plastics compounders and processors with medium-to-high testing volumes — typically facilities running 10 or more plastic tensile tests per day."],
  ["What is the typical ROI for a CubeTen?", "Most customers achieve a full return on investment in 18–24 months, driven by recovering up to 95% of technician testing time and by reducing costly scrap and rework through eliminating operator-induced variability."],
  ["How do I access and visualize my test data?", "Every test delivers stress-strain curves, shear and peel data, and in-depth raw data for each specimen. Results can be reviewed on the machine's touchscreen or in the cloud-based LabsCubed Portal, and our software team integrates directly with your existing systems, including Alpha Workbench, Uncountable, SAP and other LIMS/ERP platforms."],
  ["What is the difference between the CubeTen and the CubeOne?", "The CubeTen is engineered for rigid plastics and high-strength materials, with up to 10 kN of force and support for adhesive tests like Single Lap Shear and T-Peel. The CubeOne is built for rubber and elastomers, with up to 1 kN of force and optimized for high-elongation materials."],
  ["Does the horizontal design affect accuracy compared to vertical UTMs?", "No. LabsCubed has 10 years of comparative test data showing that our horizontal orientation delivers results identical to traditional vertical machines. The design is what enables high-speed robotic loading, and each system is precision-calibrated so gravity and friction have no impact on load readings."],
  ["At what temperature does the CubeTen test?", "The CubeTen is optimized for high-throughput testing at standard laboratory ambient temperatures. We do not currently support extreme high- or low-temperature testing, such as environmental chambers."],
  ["What does onboarding and support look like?", "We offer a white-glove setup: a LabsCubed specialist performs on-site installation, calibration to ASTM standards and team training. After installation, we provide prompt remote support and annual on-site calibration services to keep your CubeTen at peak performance."],
];
