/* Markdown for Agents — content negotiation on every page.
 *
 * A request whose Accept header asks for text/markdown gets the page's
 * Markdown copy (dist/<page>.md, generated by
 * scripts/build-agent-files.mjs) with Content-Type: text/markdown and an
 * x-markdown-tokens estimate. Everything else — every browser — passes straight
 * through to the normal HTML, which also carries `Vary: Accept` so a cache never
 * hands one representation to the other kind of client.
 *
 * Asset paths are excluded in `config` below so the function never runs for
 * them. */
import type { Config, Context } from '@netlify/edge-functions';

const wantsMarkdown = (accept: string) =>
  /(^|,)\s*text\/markdown\b(?!\s*;\s*q=0(\.0+)?\s*(,|$))/i.test(accept);

export default async (request: Request, context: Context) => {
  const accept = request.headers.get('accept') || '';
  if (request.method === 'GET' && wantsMarkdown(accept)) {
    const url = new URL(request.url);
    // Pages build flat (about-us.html), so /about-us -> /about-us.md.
    const path = url.pathname.replace(/\.html$/, '').replace(/\/+$/, '') || '/';
    const md = await fetch(new URL(path === '/' ? '/index.md' : `${path}.md`, url.origin));
    if (md.ok) {
      const text = await md.text();
      return new Response(text, {
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
          'x-markdown-tokens': String(Math.ceil(text.length / 4)),
          'Vary': 'Accept',
          'Cache-Control': 'public, max-age=0, must-revalidate',
          'Link': `<${url.origin}${path === '/' ? '/' : path}>; rel="canonical"`,
        },
      });
    }
  }
  const res = await context.next();
  const type = res.headers.get('content-type') || '';
  if (!type.includes('text/html')) return res;
  const headers = new Headers(res.headers);
  const vary = headers.get('vary');
  headers.set('Vary', vary ? `${vary}, Accept` : 'Accept');
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
};

export const config: Config = {
  path: '/*',
  excludedPath: [
    '/_astro/*', '/assets/*', '/uploads/*', '/ics/*', '/api/*', '/.netlify/*', '/.well-known/*',
    '/*.md', '/*.txt', '/*.xml', '/*.json', '/*.svg', '/*.ico', '/*.png', '/*.jpg', '/*.webp', '/*.mp4', '/*.pdf', '/*.woff2',
  ],
};
